customhost = "database-3.cnsyh4ut6ejh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "limweien-bucket"
customregion = "us-east-1f"
