customhost = "employee.c0o4z4l7q5b5.us-east-1.rds.amazonaws.com?"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "choolimin-employee"
customregion = "us-east-1"
